---
- hosts: arista

  vars:
    vlans:
      - vlanid: 2
        name: finance
      - vlanid: 3
        name: development
      - vlanid: 4
        name: frontend

  tasks:
    - name: create vlans
      eos_vlan:
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
        host:     "{{ eapi_hostname }}"
        transport: https
        port:     "{{ eapi_port }}"
        vlanid: "{{ item.vlanid }}"
        name: "{{ item.name }}"
        state: present
      with_items: "{{ vlans }}"
